import typing as t


class WorkflowExecutionStore:
    """
    Persists final workflow execution metadata + results snapshot.
    Does NOT store in-progress state (that lives in DagOrchestrator).
    """
    async def save_metadata(self, workflow_id: str, data: dict[str, t.Any]) -> None: ...
    async def save_results(self, workflow_id: str, results: dict[str, t.Any]) -> None: ...
    async def load_metadata(self, workflow_id: str) -> dict[str, t.Any] | None: ...
    async def load_results(self, workflow_id: str) -> dict[str, t.Any] | None: ...
    async def delete(self, workflow_id: str) -> None: ...