import typing as t

from .messages import ResultMessage, TaskMessage


class Transport(t.Protocol):
    async def init(self): ...
    async def publish_task(self, task: TaskMessage) -> None: ...
    async def publish_result(self, result: ResultMessage) -> None: ...
    async def subscribe_tasks(self) -> t.AsyncIterator[TaskMessage]: ...
    async def subscribe_results(self) -> t.AsyncIterator[ResultMessage]: ...
