import typing as t


class IdempotencyStore(t.Protocol):
    async def set_if_absent(self, key: str, ttl_seconds: int | None = None) -> bool: ...
    async def exists(self, key: str) -> bool: ...
    async def delete(self, key: str) -> None: ...
